<?php
    $lang['number']   = 'Číslo';
    $lang['date']     = 'Datum';
    $lang['time']     = 'Čas';
    $lang['due']      = 'Splatnost';
    $lang['to']       = 'Odběratel';
    $lang['from']     = 'Poskytovatel';
    $lang['product']  = 'Položka';
    $lang['qty']      = 'Počet';
    $lang['price']    = 'Cena';
    $lang['discount'] = 'Sleva';
    $lang['vat']      = 'DPH';
    $lang['total']    = 'Celkem';
    $lang['page']     = 'Strana';
    $lang['page_of']  = '/';
